### ISSUE TITLE
Footnotes don't work in the main title

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-un#54]
Footnotes referenced directly in the main title don't work properly.

*For example:*
````
= Annotated provisional agenda footnote:[text1], footnote:[text2]

:doctype: agenda
:committee: Centre for Trade Facilitation and Electronic Business
...
````
*Output:*
![capture-title-footnote](https://user-images.githubusercontent.com/33627611/79812577-57f7dd80-8347-11ea-8d6c-5f718ce82336.PNG)

This situation is present in the following UN sample doc: 
[ECE_AGAT_2020_INF1.zip](https://github.com/metanorma/metanorma-un/files/4507005/ECE_AGAT_2020_INF1.zip)

**Comment by opoudjis** [comment]
This has come up before. While it is possible to do some freaky stuff to process such a footnote, its rendering will be a disaster: isodoc will certainly have no idea where to put such a footnote, and we will have to do extra special processing, because the coverpage is involved. In fact, I think it would be more productive to mark it up as a special type of note, that we dump into the coverpage in postprocessing.

**Comment by opoudjis** [comment]
OTOH, the cover page is dealing with footnotes in the abstract...

**Comment by opoudjis** [comment]
Well, this is strange. I am sending the titles to asciidoctor sub, to expand out markup in titles, particularly in UN, where titles have markup. But by the time I do so, all the markup *has* already been expanded out into Metanorma XML, including the footnotes; so instead of expanding out the macros, the markup in the titles is all HTML-escaped. I wonder if this was an asciidoctor 2.0 upgrade.

... Looks like it: https://github.com/asciidoctor/asciidoctor/issues/3106

In fact, we have a difference in behaviour between node.title and node.attr("title"): the former (the initial `= Title` of an asciidoctor document) has had substitutions applied to it, so it is resolved into Metanorma XML; the latter does not. Will need to update all gems processing node.title for the document.

**Comment by opoudjis** [comment]
So, now the title text is processed correctly. But the footnotes have disappeared...

**Comment by opoudjis** [comment]
Not so fast:

* attribute footnotes are still being utterly mangled by asciidoc_sub
* footnotes in titles are correct in the XML, but mangled in the HTML rendering. And that is to be expected on the coverpage, since they are dropped in in Liquid templating. It is impossible to circumvent this in current architecture.

I very strongly recommend we not support footnotes in document titles.

**Comment by opoudjis** [comment]
footnotes are being mangled in the document attributres, because asciidoc_sub is processing substitutes via a generic Asciidoc instance, so it is unaware of Metanorma or flavour-specific macros, such as the Metanorma treatment of footnotes. Remedying that by making the Asciidoc instance a standoc document.

**Comment by opoudjis** [comment]
Solution: Title footnotes are a special kind of note, that are rendered post facto as footnotes on the title. If title appears twice in a document, as is routine in ISO, the title note needs only be rendered once.

**Comment by opoudjis** [comment]
So I will move any footnotes on titles into bibdata notes. We will not allow footnotes at arbitrary locations within a title, since the processing is just too difficult.

**Comment by opoudjis** [comment]
In the source document, these have been realised as numbers. I am not doing so, because footnotes on the title have to be extraneous to the main flow of footnotes in the document—because of how the coverpage and titles are handled separately.
